
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.17.0
//      You can make changes to this file and they will not be overwritten when saving.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace To_Dewey{
    using Terminal.Gui;
    
    
    public partial class MyView {
        static List<Entry> notes = new List<Entry>();
        static int index = -1;
        
        public MyView() {
            InitializeComponent();
            MakeStatusBar();
            button1.Accepting += (s, e) => {
                MessageBox.Query("Hello", "Hello There!", "Ok");
            };             
        }
    }
}
