
//------------------------------------------------------------------------------

//  <auto-generated>
//      This code was generated by:
//        TerminalGuiDesigner v1.0.18.0
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// -----------------------------------------------------------------------------
namespace To_Dewey {
    using System;
    using Terminal.Gui;
    
    //MyView.cs and MyViewDesigner are for one window only.

    public partial class MyView : Terminal.Gui.Window {
        
        private Terminal.Gui.Label label1;
        private Terminal.Gui.Button button1;
        private Terminal.Gui.Bar statusBar;
        
        private void InitializeComponent() {
            this.button1 = new Terminal.Gui.Button();
            this.label1 = new Terminal.Gui.Label();

            this.Width = Dim.Fill();
            this.Height = Dim.Fill();
            this.X = 0;
            this.Y = 0;

            this.Title = "Press Esc to quit";

            this.label1.Width = 11;
            this.label1.Height = 1;
            this.label1.X = Pos.Center();
            this.label1.Y = Pos.Center();
            this.label1.Data = "label1"; //no function; remove
            this.label1.Text = "Hello World";
            this.label1.TextAlignment = Alignment.Center;
            this.Add(this.label1);

            this.button1.Width = 12;
            this.button1.X = Pos.Center();
            this.button1.Y = Pos.Center() + 1;
            this.button1.Data = "button1"; //no function; remove
            this.button1.Text = "Click Me";
            this.button1.TextAlignment = Alignment.Center;
            this.button1.IsDefault = false;
            this.Add(this.button1);
        }

        private void MakeStatusBar(){
            this.statusBar = new Bar() {
                X = 0,
                Y = Pos.AnchorEnd(1),
                Width = Dim.Fill(),
                Height = 1
            };

            statusBar.Add(new Shortcut(Key.N, "_New Note", () => {/*Add reference to function that takes use to a window/popup to add a new note.*/}));
            this.Add(this.statusBar);
        }
    }
}
